import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Inter, Playfair_Display } from "next/font/google";
import Header from "@/app/header";
import Footer from "@/app/footer";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "700"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Joji'trips",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html
        lang="en"
        className={`relative min-h-screen bg-gallery-white text-gallery-dark font-sans antialiased ${inter.variable} ${playfairDisplay.variable}`}
      >
        <body className={inter.className}>
          <div className="w-full flex justify-center">
            <Header />
          </div>
          <div className="mb-16 pt-20">{children}</div>
          <Footer />
          <SpeedInsights />
        </body>
      </html>
    </>
  );
}
