// Importa il tipo Metadata da Next.js per definire i metadati della pagina (es. titolo, descrizione)
import type { Metadata } from "next";
// Importa il componente per monitorare le performance del sito con Vercel
import { SpeedInsights } from "@vercel/speed-insights/next";
// Importa i font di Google (Inter e Playfair Display) per ottimizzarne il caricamento
import { Inter, Playfair_Display } from "next/font/google";
// Importa i componenti Header e Footer creati nel progetto
import Header from "@/app/header";
import Footer from "@/app/footer";
// Importa il file CSS globale che contiene gli stili di base e Tailwind
import "./globals.css";

// Configura il font Inter (sans-serif)
const inter = Inter({
  subsets: ["latin"], // Carica solo i caratteri latini per ridurre il peso
  variable: "--font-inter", // Definisce una variabile CSS per usare questo font in Tailwind
});

// Configura il font Playfair Display (serif)
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  style: ["normal", "italic"], // Carica sia lo stile normale che corsivo
  weight: ["400", "700"], // Carica i pesi "regular" (400) e "bold" (700)
  variable: "--font-playfair",
});

// Oggetto metadata esportato: Next.js lo usa per generare i tag <head> (SEO)
export const metadata: Metadata = {
  title: "Joji'trips",
  description: "Generated by create next app",
};

// Questo è il RootLayout, ovvero il componente base che racchiude tutte le pagine dell'app.
// Ogni pagina che crei (il parametro 'children') verrà inserita all'interno di questo layout.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* Il tag <html> è il contenitore principale. Applichiamo le variabili CSS dei font qui. */}
      <html
        lang="en"
        className={`relative min-h-[100dvh] bg-gallery-white text-gallery-dark font-sans antialiased ${inter.variable} ${playfairDisplay.variable}`}
      >
        {/* Applichiamo il font principale "Inter" a tutto il corpo del documento */}
        <body className={inter.className}>
          <div className="w-full flex justify-center">
            {/* L'intestazione (Header) appare in alto in tutte le pagine */}
            <Header />
          </div>

          {/* Questo 'children' è il contenuto specifico di ogni singola pagina (es. la Home o About) */}
          <div className="mb-16 pt-20">{children}</div>

          {/* Il piè di pagina (Footer) appare in basso in tutte le pagine */}
          <Footer />

          {/* Inizializza Vercel Speed Insights per misurare le performance */}
          <SpeedInsights />
        </body>
      </html>
    </>
  );
}
