import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import Header from "@/app/header";
import Footer from "@/app/footer";
import "./globals.css";

const garamond = Cormorant_Garamond({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" className="relative">
        <body className={garamond.className}>
          <Header />
          <div className="mb-16">{children}</div>
          <Footer />
        </body>
      </html>
    </>
  );
}
