import { expect, test, describe } from "bun:test";
import getTitleAndDescMetadata from "./getTitleAndDescMetadata";

describe("getTitleAndDescMetadata", () => {
  test("should return the correct metadata object", () => {
    const metadata = getTitleAndDescMetadata();

    expect(metadata).toEqual({
      title: "Joji'trips",
      description: "Generated by create next app",
    });
  });

  test("should return an object with title and description properties", () => {
    const metadata = getTitleAndDescMetadata();

    expect(metadata).toHaveProperty("title");
    expect(metadata).toHaveProperty("description");
    expect(typeof metadata.title).toBe("string");
    expect(typeof metadata.description).toBe("string");
  });
});
