export interface Metadata {
  title: string;
  description: string;
}

const getTitleAndDescMetadata = (): Metadata => ({
  title: "Joji'trips",
  description: "Generated by create next app",
});

export default getTitleAndDescMetadata;
